version: '3.3'

services:

  Tachira_p1:
    container_name: ${DB_NAME}
    image: "postgres:17-bullseye"
    restart: always
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    # volumes: 
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

# volumes: 
#   postgres_data: 
#     driver: local